apiVersion: v1
kind: Pod
metadata: 
  name: result-pod
  labels:
    name: result-pod
    app: demo-voting-app

spec:
  containers:
    - name: result-pod
      image: dockersamples/examplevotingapp_result
      ports:
       - containerPort: 80